// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL_3zldGjToT339vnUUod4E5AzZ_DF4vk',
    appId: '1:13314015555:web:e312e677fcee31c1df6ff6',
    messagingSenderId: '13314015555',
    projectId: 'e-market-1723',
    authDomain: 'e-market-1723.firebaseapp.com',
    storageBucket: 'e-market-1723.firebasestorage.app',
    measurementId: 'G-8TNZBWS1C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCALG5pqS6vu10IM1GT0ECNwdCTnxuMWg',
    appId: '1:13314015555:android:6ed3b7e490229a99df6ff6',
    messagingSenderId: '13314015555',
    projectId: 'e-market-1723',
    storageBucket: 'e-market-1723.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbXKNRpfVsRku_9xtXCBFfvfEKtYKzWIc',
    appId: '1:13314015555:ios:59881afc9bdf8fbbdf6ff6',
    messagingSenderId: '13314015555',
    projectId: 'e-market-1723',
    storageBucket: 'e-market-1723.firebasestorage.app',
    iosBundleId: 'com.example.eMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbXKNRpfVsRku_9xtXCBFfvfEKtYKzWIc',
    appId: '1:13314015555:ios:59881afc9bdf8fbbdf6ff6',
    messagingSenderId: '13314015555',
    projectId: 'e-market-1723',
    storageBucket: 'e-market-1723.firebasestorage.app',
    iosBundleId: 'com.example.eMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL_3zldGjToT339vnUUod4E5AzZ_DF4vk',
    appId: '1:13314015555:web:c9597ad3a1b6c3fcdf6ff6',
    messagingSenderId: '13314015555',
    projectId: 'e-market-1723',
    authDomain: 'e-market-1723.firebaseapp.com',
    storageBucket: 'e-market-1723.firebasestorage.app',
    measurementId: 'G-B024YV43VX',
  );

}